source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

pod 'TXSwizzling', "~>1.0.2"

target 'TXDragAndDrop_Example', :exclusive => true do
  pod "TXDragAndDrop", :path => "../"
end

target 'TXDragAndDrop_Tests', :exclusive => true do
  pod "TXDragAndDrop", :path => "../"

  pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'

end
